"""
Pydantic models representing SLAM Local Maps, KeyFrames, and MapPoints.
"""
import time
from typing import List, Dict, Optional
from pydantic import BaseModel, Field
from app.models.glass import GlassPose


class MapPoint(BaseModel):
    """3D spatial landmark point generated by Monocular+IMU SLAM."""
    point_id: str = Field(..., description="Unique landmark point identifier")
    x: float = Field(..., description="Global X 3D coordinate (meters)")
    y: float = Field(..., description="Global Y 3D coordinate (meters)")
    z: float = Field(..., description="Global Z 3D coordinate (meters)")
    descriptor: List[float] = Field(default_factory=list, description="Feature descriptor vector")
    observed_count: int = Field(default=1, description="Number of keyframe observations")


class KeyFrame(BaseModel):
    """SLAM KeyFrame capturing camera pose, timestamp, and landmark observations."""
    keyframe_id: str = Field(..., description="Unique keyframe identifier")
    glass_id: str = Field(..., description="Smart glass device identifier")
    pose: GlassPose = Field(..., description="Camera 6DoF pose at keyframe creation")
    map_point_ids: List[str] = Field(default_factory=list, description="IDs of observed map points")
    timestamp: float = Field(default_factory=time.time, description="Creation timestamp")


class LocalMap(BaseModel):
    """Local SLAM map built independently by an individual smart glass unit."""
    glass_id: str = Field(..., description="Owner smart glass device identifier")
    map_id: str = Field(..., description="Unique map identifier")
    keyframes: Dict[str, KeyFrame] = Field(default_factory=dict, description="Keyframes in local map")
    map_points: Dict[str, MapPoint] = Field(default_factory=dict, description="3D landmark map points")
    last_loop_closure_ts: Optional[float] = Field(default=None, description="Timestamp of last loop closure")
